FROM node:21 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/build /var/www/bucket

RUN chown -R nginx:nginx /var/www/bucket

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]